//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterEmployee", ReplyAction="http://tempuri.org/IService1/RegisterEmployeeResponse")]
    string RegisterEmployee();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterEmployee", ReplyAction="http://tempuri.org/IService1/RegisterEmployeeResponse")]
    System.Threading.Tasks.Task<string> RegisterEmployeeAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployee", ReplyAction="http://tempuri.org/IService1/GetEmployeeResponse")]
    string GetEmployee(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployee", ReplyAction="http://tempuri.org/IService1/GetEmployeeResponse")]
    System.Threading.Tasks.Task<string> GetEmployeeAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string RegisterEmployee()
    {
        return base.Channel.RegisterEmployee();
    }
    
    public System.Threading.Tasks.Task<string> RegisterEmployeeAsync()
    {
        return base.Channel.RegisterEmployeeAsync();
    }
    
    public string GetEmployee(string name)
    {
        return base.Channel.GetEmployee(name);
    }
    
    public System.Threading.Tasks.Task<string> GetEmployeeAsync(string name)
    {
        return base.Channel.GetEmployeeAsync(name);
    }
}
